### ISSUE TITLE
Bot无法发送消息

### ISSUE THREAD

**Issue by FrandreJoestar** [XTxiaoting14332/nonebot-plugin-phigros#1]
后台响应了消息，但是QQ中并没有发送出来消息
![image](https://github.com/XTxiaoting14332/nonebot-plugin-phigros-qq/assets/118864715/1938c08b-b9c5-4d89-8141-73349880fd99)
![image](https://github.com/XTxiaoting14332/nonebot-plugin-phigros-qq/assets/118864715/c3ad20e7-7a20-45f5-bf12-93d568cc3ace)

**Comment by XTxiaoting14332** [comment]
你需要用adapter-qq而不是其他的适配器 后续我会更新其他的适配

**Comment by XTxiaoting14332** [comment]
已支持其他适配器
请先卸载``nonebot-plugin-phigros-qq``
然后根据文档通过``pip安装``或``Github下载``的方式安装新版本的``nonebot-plugin-phigros``（因为插件信息暂未在商店同步，所以无法使用``nb-cli``进行安装）
